# fly.toml app configuration file generated for preston-website on 2024-12-13T23:41:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
#  flyctl scale count 0 # keep it at 1 always
#  flyctrl deploy

app = 'preston-website'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
